<?php if(isset($_GET['cad']) && $_GET['cad'] == 'ok'){ ?>
<div class="alert alert-success text-center" role="alert">
  Cadastrado com sucesso!
</div>
<?php } ?>
<?php if(isset($_GET['cad']) && $_GET['cad'] == 'erro'){ ?>
<div class="alert alert-danger text-center" role="alert">
 Erro no cadastro, verifique sua conexão ou os campos!
</div>
<?php } ?>
<div class="text-center">
	<h1 class="h2">Cadastro de Alunos</h1>
</div>
<hr>

<div class="container border">
<form method="post" action="/registrar?acao=aluno"> 
    <div class="row  pt-4">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="inputNome" class="sr-only" >Nome do Aluno:</label>
                    <input class="form-control" type="text" id="inputNome" placeholder="Nome do Aluno" autofocus required name="nome_aluno">
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label for="inputRm" class="sr-only" >RM do Aluno:</label>
                    <input class="form-control" type="number" id="inputRm" placeholder="RM do Aluno" required name="rm_aluno">
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label for="inputData" class="sr-only" >Data de nascimento do Aluno:</label>
                    <input class="form-control" type="date" id="inputData" placeholder="" required name="data_aluno">
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label for="inputEscolaridade" class="sr-only" >Escolaridade do Aluno:</label>
                    <select class="custom-select" id="inputGroupSelect01" required name="escolaridade">
                        <option value="Ensino Fundamental(1ºano)" selected>Ensino Fundamental(1ºano)</option>
                        <option value="Ensino Fundamental(2ºano)">Ensino Fundamental(2ºano)</option>
                        <option value="Ensino Fundamental(3ºano)">Ensino Fundamental(3ºano)</option>
                        <option value="Ensino Fundamental(4ºano)">Ensino Fundamental(4ºano)</option>
                        <option value="Ensino Fundamental(5ºano)">Ensino Fundamental(5ºano)</option>
                        <option value="Ensino Fundamental(6ºano)">Ensino Fundamental(6ºano)</option>
                        <option value="Ensino Fundamental(7ºano)">Ensino Fundamental(7ºano)</option>
                        <option value="Ensino Fundamental(8ºano)">Ensino Fundamental(8ºano)</option>
                        <option value="Ensino Fundamental(9ºano)">Ensino Fundamental(9ºano)</option>
                        <option value="Ensino Médio(1ºano)">Ensino Médio(1ºano)</option>
                        <option value="Ensino Médio(2ºano)">Ensino Médio(2ºano)</option>
                        <option value="Ensino Médio(3ºano)">Ensino Médio(3ºano)</option>
                    </select>
                </div>
            </div>     
        
            <div class="container-fluid pb-4">
                <button class="btn btn-danger col-md-5 float-left pt-3 pb-3" onclick="alert('cancelado!')">Cancelar</button>
                <button class="btn btn-success col-md-5 float-right pt-3 pb-3">Cadastrar Aluno</button>
            </div>
        </div>
            
                
    </form>
    <br />
    <br />
    <h3>Alunos cadastrados:</h3>
    <table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">RM</th>
      <th scope="col">NOME</th>
      <th scope="col">DATA DE NASCIMENTO</th>
      <th scope="col">ESCOLARIDADE</th>
      <th scope="col">Ações</th>
    </tr>
  </thead>
  <tbody>
<?php foreach ($this->view->alunos as $key => $aluno) { ?>
    <tr >
      <th scope="row"><?= ($key+1) ?></th>
      <td><?= $aluno['rm'] ?></td>
      <td><?= $aluno['nome'] ?></td>
      <td><?= $aluno['data'] ?></td>
      <td><?= $aluno['escolaridade'] ?></td>
      <form method="post" action="/remover?acao=aluno">
          <td><button onclick="return remover()" class="btn btn-danger" value="<?= $aluno['id'] ?>" name="id">Apagar</button></td>
      </form>
    </tr>

<?php } ?>

    
  </tbody>
</table>


</div>
<script type="text/javascript">
  function remover() {
    if(confirm('Você deseja mesmo remover?')){
      return true;
    }else {
      return false
    }
  }

</script>