<?php if(isset($_GET['cad']) && $_GET['cad'] == 'ok'){ ?>
<div class="alert alert-success text-center" role="alert">
  Cadastrado com sucesso!
</div>
<?php }?>
<?php if(isset($_GET['cad']) && $_GET['cad'] == 'erro'){ ?>
<div cs="alert ass="alert alert-danger text-center" role="alert">
 Erro no cadastro, verifique sua conexão ou os campos!
</div>
<?php } ?>
<div class="text-center">
  <h1 class="h2">Cadastro de Funcionários</h1>  
</div>
<hr>

<div class="container border">
<form method="post" action="/registrar?acao=funcionario"> 
    <div class="row  pt-4">
        
            <div class="col-md-6">
                <div class="form-group">
                    <label for="inputNome" class="sr-only" >Nome do Funcionário:</label>
                    <input class="form-control" type="text" id="inputNome" placeholder="Nome do Funcionário" autofocus required name="nome"> 
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="inputEscolaridade" class="sr-only" >Cargo do Funcionário:</label>
                    <select class="custom-select" id="inputGroupSelect01" required name="funcao">
                        
                        <option value="Faxineiro(a)" selected>Faxineiro(a)</option>
                        <option value="Diretor(a)">Diretor(a)</option>
                        <option value="Cordenador(a)">Cordenador(a)</option>
                        <option value="Atendente">Atendente</option>
                    </select>
                </div>
            </div>     
        
            <div class="container-fluid pb-4">
                <button class="btn btn-danger col-md-5 float-left pt-3 pb-3">Cancelar</button>
                <button class="btn btn-success col-md-5 float-right pt-3 pb-3">Cadastrar Funcionário</button>
            </div>
        </div>
            
                
    </form>
  <table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">NOME</th>
      <th scope="col">FUNÇÃO</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($this->view->funcionarios as $key => $funcionario) { ?>
    <tr>
      <th scope="row"><?= ($key + 1) ?></th>
      <td><?= $funcionario['nome'] ?></td>
      <td><?= $funcionario['funcao'] ?></td>
    </tr>
  <?php } ?>
  </tbody>
</table>

</div>
