<section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">Sistema Escolar</h1>
          <p class="lead text-muted">Praticidade nos cadastros é o nosso foco!</p>
          <p>
            <a target="_blank" href="https://www.facebook.com/paulo.leite.71271466?ref=bookmarks" class="btn btn-primary my-2">Conheça o Paulo (criador)</a>
            <a target="_blank" href="https://www.facebook.com/ermesom.matheus.7" class="btn btn-secondary my-2">Conheça o Ermesom(ajudante técnico)</a>
          </p>
        </div>
</section>